---
- name: Create the awx user on the tower host and generate a new ssh key
  hosts: tower
  gather_facts: no
  become: yes

  tasks:
    - name: Create awx group
      group:
        name: "{{ awx_user }}"
        gid: 1010

    - name: Add awx user to the awx group
      user:
        name: "{{ awx_user }}"
        comment: Ansible AWX
        uid: 1010
        group: "{{ awx_group }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: ".ssh/{{ awx_priv_ssh_key_filename }}"
      register: awx_user_results

    - name: Print public key
      debug:
        msg: "{{ awx_user_results.ssh_public_key }}"

    # become false prevents "Failed to get information on remote file (./files/id_rsa_awx.pub): sudo: a password is required"
    - name: Copy awx generated public key content to the local files directory
      copy:
        content: "{{ awx_user_results['ssh_public_key'] }}"
        dest: "{{ awx_pub_local_ssh_key_path }}"
      delegate_to: localhost
      become: false
