---
- src: geerlingguy.repo-epel
  version: 1.2.4
- src: geerlingguy.git
  version: 2.0.5
- src: geerlingguy.ansible
  version: 2.0.1
- src: geerlingguy.docker
  version: 2.5.2
- src: geerlingguy.pip
  version: 1.3.0
- src: geerlingguy.nodejs
  version: 5.0.0
- src: geerlingguy.awx
  version: 1.2.0
